#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ionicbackend.Global
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class backendDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
        #endregion
        public backendDataContext() :
                base(global::System.Configuration.ConfigurationManager.ConnectionStrings["backendConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public backendDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public backendDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public backendDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public backendDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.USP_TL_CheckLogin")]
        public ISingleResult<CommonResult> USP_TL_CheckLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "EXPRESSION", DbType = "VarChar(1000)")] string eXPRESSION)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eXPRESSION);
            return ((ISingleResult<CommonResult>)(result.ReturnValue));
        }
        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.USP_AddUser")]
        public int USP_AddUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "SearchCondition", DbType = "VarChar(MAX)")] string searchCondition, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ID", DbType = "Int")] ref System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "ERROR_ID", DbType = "Int")] ref System.Nullable<int> eRROR_ID)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchCondition, iD, eRROR_ID);
            iD = ((System.Nullable<int>)(result.GetParameterValue(1)));
            eRROR_ID = ((System.Nullable<int>)(result.GetParameterValue(2)));
            return ((int)(result.ReturnValue));
        }
    }
    public partial class CommonResult
    {

        private string _JSON_F52E2B61_18A1_11d1_B105_00805F49916B;

        public CommonResult()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Name = "[JSON_F52E2B61-18A1-11d1-B105-00805F49916B]", Storage = "_JSON_F52E2B61_18A1_11d1_B105_00805F49916B", DbType = "NVarChar(MAX)")]
        public string JSON_F52E2B61_18A1_11d1_B105_00805F49916B
        {
            get
            {
                return this._JSON_F52E2B61_18A1_11d1_B105_00805F49916B;
            }
            set
            {
                if ((this._JSON_F52E2B61_18A1_11d1_B105_00805F49916B != value))
                {
                    this._JSON_F52E2B61_18A1_11d1_B105_00805F49916B = value;
                }
            }
        }
    }
}
#pragma warning restore 1591
